language: python
python: '2.7'
install:
- mkdir -p buildout-cache/eggs
- mkdir -p buildout-cache/downloads
- easy_install -U setuptools
- python bootstrap.py -c travis.cfg
- ./bin/buildout -N -t 3 -c travis.cfg
script: ./bin/test
